logging:
  level:
    sql: debug
    jdbc: debug
    jdbc.sqlonly: debug
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug
        security: DEBUG

  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n"
    file: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n"

server:
  port: 7007
  compression:
    enabled: true # ?? ?? ?? ??.
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript

spring:
  application:
    name: bgpdemo

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bgp.re.kr
          jwk-set-uri: http://bgp.re.kr

  datasource:
    url: jdbc:postgresql://localhost:5432/jpademo
    username: jpademo
    password: jpademo

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

jwt:
  private:
    key: classpath:jwt/private_key.key
  public:
    key: classpath:jwt/public_key.pub