version: '2'

services:
  postgresql:
    container_name: postgres
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - './pgdata:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=changeit

volumes:
  pgdata:
    driver: local
